### ISSUE TITLE
Windows 10 / error in pyspectator setup command: 'install_requires' ...Invalid requirement, parse error at "'-r base.'"

### ISSUE THREAD

**Issue by StudioPolygon** [it-geeks-club/pyspectator#23]
I have problems installing pyspectator...
C:\Users\mathias>pip install pyspectator
Collecting pyspectator
  Using cached https://files.pythonhosted.org/packages/96/04/7ced429c14e26fe44d121ce4517b8894491f732b46e482d5067320b1e3b9/pyspectator-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    error in pyspectator setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-r base.'"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mathias\AppData\Local\Temp\pip-install-v57txfup\pyspectator\

C:\Users\mathias>
C:\Users\mathias>pip --version
pip 18.0 from c:\python37\lib\site-packages\pip (python 3.7)

C:\Users\mathias>python --version
Python 3.7.0

C:\Users\mathias>

**Comment by naurion** [comment]
1. Download source archive.
2. unpack it and change file "pyspectator-1.2.1\requirements\windows.txt" like that:
psutil>=2.1.1
netifaces>=0.10.4
pyvalid>=0.9
pytest>=2.6.2
enum34>=1.0
wmi >= 1.4.9

3. then in terminal: python setup.py install

p.s. Install Microsoft Visual C++ Build Tools before.

p.s.s Sorry for my english

**Comment by uzumaxy** [comment]
Hey @naurion, @Carthago44, @StudioPolygon,
Sorry for huge delay with response. Issue should be fixed in the 1.2.2 version. Please let me know if you'll face any similar problems again.
Thanks!
