### ISSUE TITLE
Error "Can't read CPU temperature".

### ISSUE THREAD

**Issue by ghost** [it-geeks-club/pyspectator#28]
Hello. There was such a problem, I used this code:
from pyspectator.processor import Cpu
from time import sleep
cpu = Cpu(monitoring_latency=1)
with cpu:
    for _ in range(8):
        cpu.load, cpu.temperature
        sleep(1.1)
But here is what is output:
Can't read CPU temperature
How can I solve this problem? Thank you in advance.

**Comment by thalesgreco** [comment]
Try to run the script as Administrator

**Comment by ghost** [comment]
Thank You, Worked!
